fix: change workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,37 +1,27 @@
-# .github/workflows/python-ci.yml
-name: Python CI
+name: CI Pipeline
 
 on:
   push:
     branches:
       - main
   pull_request:
-  schedule:
-    - cron: "0 0 * * *"  # Runs every day at midnight UTC; adjust as needed
-  workflow_dispatch:  # Allows manual triggering
+    branches:
+      - main
 
 jobs:
-  
-  test:
+  setup:
+    name: Setup Database
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout source
+      - name: Checkout code
         uses: actions/checkout@v4
-
+      
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'
 
-      - name: Cache pip dependencies
-        uses: actions/cache@v4
-        with:
-          path: .cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
-
-      - name: Install dependencies and create virtual environment
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install virtualenv
@@ -39,240 +29,160 @@ jobs:
           source venv/bin/activate
           pip install .[test]
       
-      - name: Install SPARQLWrapper
-        run: pip install SPARQLWrapper
-
-      - name: Run tests with Tox
+      - name: Setup database
         run: |
-          source venv/bin/activate
-          tox -e py
-
-      - name: Upload test results
-        if: always()
-        uses: actions/upload-artifact@v4
+          mkdir -p src/scholaridreconciler/services/.cache/db
+          python src/scholaridreconciler/services/organisation_data.py
+      
+      - name: Cache database
+        uses: actions/cache@v4
         with:
-          name: coverage.xml
-          path: coverage.xml
-    
-      - name: upload print results
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: app.log
-          path: src/scholaridreconciler/app.log
+          path: src/scholaridreconciler/services/.cache/db
+          key: database-cache-${{ github.run_id }}
+          restore-keys: database-cache-
 
-  lint:
+  test:
+    name: Run Tests
     runs-on: ubuntu-latest
+    needs: setup
     steps:
-      - name: Checkout source
+      - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Restore database cache
+        uses: actions/cache@v4
+        with:
+          path: src/scholaridreconciler/services/.cache/db
+          key: database-cache-${{ github.run_id }}
+          restore-keys: database-cache-
 
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'
 
-      - name: Cache pip dependencies
-        uses: actions/cache@v4
-        with:
-          path: .cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
-
-      - name: Install dependencies and create virtual environment
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install virtualenv
           virtualenv venv
           source venv/bin/activate
           pip install .[test]
+      
+      - name: Run tests
+        run: tox -e py
+      
+      - name: Upload test reports
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-reports
+          path: coverage.xml
 
-      - name: Run linting with Tox
+  lint:
+    name: Run Linting
+    runs-on: ubuntu-latest
+    needs: setup
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+
+      - name: Install dependencies
         run: |
+          python -m pip install --upgrade pip
+          pip install virtualenv
+          virtualenv venv
           source venv/bin/activate
+          pip install .[test]
+      
+      - name: Run linting
+        run: |
           tox -e format
           tox -e lint
 
   coverage:
+    name: Check Test Coverage
     runs-on: ubuntu-latest
+    needs: setup
     steps:
-      - name: Checkout source
+      - name: Checkout code
         uses: actions/checkout@v4
-
+      
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'
-
-      - name: Cache pip dependencies
-        uses: actions/cache@v4
-        with:
-          path: .cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
-
-      - name: Install dependencies and create virtual environment
+      
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install virtualenv
           virtualenv venv
           source venv/bin/activate
           pip install .[test]
-
-      - name: Run coverage with Tox
-        run: |
-          source venv/bin/activate
-          tox -e coverage
-
-      - name: Upload coverage report
-        if: always()
+      
+      - name: Run coverage
+        run: tox -e coverage
+      
+      - name: Upload Coverage Report
         uses: actions/upload-artifact@v4
         with:
-          name: coverage.xml
+          name: coverage-report
           path: coverage.xml
+      
+      - name: Report Coverage
+        run: |
+          grep -E '(?i)total.*? (100(?:\.0+)?%|[1-9]?\d(?:\.\d+)?%)$' coverage.xml || true
 
   type_check:
+    name: Static Type Check
     runs-on: ubuntu-latest
     continue-on-error: true
     steps:
-      - name: Checkout source
+      - name: Checkout code
         uses: actions/checkout@v4
-
+      
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'
-
-      - name: Cache pip dependencies
-        uses: actions/cache@v3
-        with:
-          path: .cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
-
-      - name: Install dependencies and create virtual environment
+      
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install virtualenv
           virtualenv venv
           source venv/bin/activate
           pip install .[test]
+      
+      - name: Run type checks
+        run: tox -e type
 
-      - name: Run type checks with Tox
-        run: |
-          source venv/bin/activate
-          tox -e type
-
-  commit-check:
+  commit_check:
     name: Validate Commit Messages
-    needs: test
     runs-on: ubuntu-latest
-
     steps:
-      # Step 1: Checkout the repository
-      - name: Checkout Repository
+      - name: Checkout code
         uses: actions/checkout@v4
-        with:
-          fetch-depth: 0  # Fetch all history for all branches and tags
-
-      # Step 2: Install Git (if not already available)
-      - name: Install Git
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y git
-
-      # Step 3: Validate Commit Messages
+      
       - name: Validate Commit Messages
-        id: commit_validation
-        if: ${{ github.event_name == 'push' }}
         run: |
-          echo "Validating commit messages..."
-          
-          # Get all commit messages in the push
-          COMMITS=$(git log --pretty=%s origin/main..HEAD --no-merges --reverse)
-      
-          # Define commit message pattern
-          COMMIT_PATTERN="^[Ii]nitial\scommit$|^(build|ci|docs|feat|fix|perf|refactor|style|test|revert):\s.+$|^Revert\s.+$|^Add\s(LICENSE|CHANGELOG)$|^updated python version for CI$|^Merge\sbranch\s.+$"
-          
-          # Initialize failure flag
-          FAIL=0
-          
-          # Split commits into an array
-          COMMITS_ARRAY=($COMMITS)
-          
-          # Debug: print commit messages to validate
-          echo "Commits to validate:"
-          echo "$COMMITS"
+          COMMITS=$(git log --pretty=%s HEAD~2..HEAD --no-merges --reverse)
+          IFS=$'\n'
+          COMMIT_PATTERN="^[Ii]nitial\scommit$|^\"?(build|ci|docs|feat|fix|perf|refactor|style|test|revert|update):\s.+\"?$|^Revert\s.+$|^Add\s(LICENSE|CHANGELOG)$|^updated python version for CI$|^Merge\sbranch\s.+$"
 
-          # Iterate over each commit message
-          for COMMIT in "${COMMITS_ARRAY[@]}"; do
-            # Check if commit message matches the pattern
-            if ! [[ "$COMMIT" =~ $COMMIT_PATTERN ]]; then
-              echo "Invalid commit message: '$COMMIT'"
-              FAIL=1
-            fi
-
-            # Check if commit message length exceeds 100 characters
-            COMMIT_LENGTH=${#COMMIT}
-            if [[ "$COMMIT_LENGTH" -gt 100 ]]; then
-              echo "Commit message too long ($COMMIT_LENGTH characters): '$COMMIT'"
-              FAIL=1
-            fi
+          for COMMIT in $COMMITS; do
+              if ! [[ "$COMMIT" =~ $COMMIT_PATTERN ]]; then
+                  echo "Invalid commit message: $COMMIT"
+                  exit 1
+              fi
+              if [[ ${#COMMIT} -gt 100 ]]; then
+                echo "Commit message too long (more than 100 characters): $COMMIT"
+                exit 1
+              fi
           done
-          
-          # If any failures were found, exit with error code
-          if [[ "$FAIL" -eq 1 ]]; then
-            echo "❗ Commit message validation failed."
-            exit 1
-          else
-            echo "✅ All commit messages are valid."
-          fi
-      
-  retrieve_data:
-    if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'  
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with: 
-          fetch-depth: 0
-
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.10'
-
-      - name: Install dependencies and create virtual environment
-        run: |
-          python -m pip install --upgrade pip
-          pip install virtualenv
-          virtualenv venv
-          source venv/bin/activate
-          pip install .[test]
-
-      - name: delete previous saved db file
-        run: |
-          rm -f src/scholaridreconciler/services/organisation_data.db
-
-          
-      - name: Run data retrieval script
-        run: |
-          source venv/bin/activate
-          python src/scholaridreconciler/services/organisation_data.py
-
-
-      - name: Commit and Push Changes
-        run: |
-          git config --local user.name "github-actions[bot]"
-          git config --local user.email "github-actions[bot]@users.noreply.github.com"
-          git add src/scholaridreconciler/services/organisation_data.db
-          git commit -m "feat: update data with latest data" --allow-empty
-          git push origin main
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        
-          
-      
+          unset IFS
